name: Build and Export Docker Image

on: [push]

jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t data-logger-latest .

      - name: Save Docker image as .tar file
        run: |
          docker save data-logger-latest -o data-logger.tar
          gzip data-logger.tar  # Compress to save space

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: data-logger.tar.gz
          retention-days: 7  # Automatically deleted after 7 days

      - name: Cleanup
        run: docker system prune -f
