name: Build and Push Public Image

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Still needed to push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/my-image:latest .

      - name: Push to GHCR (public)
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/my-image:latest
          # No need for login since GITHUB_TOKEN is automatically used
