name: Build Docker Image

on: [push]

env:
  IMAGE_NAME: data-logger-latest  # Typo fixed: 'lastest' → 'latest'
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} -f ${{ env.DOCKERFILE_PATH }} .

      - name: Save as artifact
        run: |
          docker save ${{ env.IMAGE_NAME }} -o image.tar
          mkdir -p docker-images
          mv image.tar docker-images/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-images/image.tar
          retention-days: 5  # Adjust as needed
